title: "jrfep"
description: "José Rafael Ferrer Paris"
# theme: jekyll-theme-hacker

collections:
  eventos:
    output: true
  presentaciones:
    output: true

defaults:
   - scope:
      path: ""
      type: "eventos"
     values:
      layout: "evento"
   - scope:
      path: ""
      type: "presentaciones"
     values:
      layout: "presentacion"
   - scope:
      path: ""
     values:
      layout: "default"
