theme: jekyll-theme-hacker
title: "jrfep"
description: "José Rafael Ferrer Paris"

collections:
  eventos:
    output: true
  presentaciones:
    output: true

defaults:
   - scope:
      path: ""
      values:
      layout: "default"
   - scope:
      path: ""
      type: "eventos"
      values:
      layout: "eventos"
   - scope:
      path: ""
      type: "presentaciones"
      values:
      layout: "presentaciones"
