project:
  type: website
  output-dir: docs

website:
  title: "./jrfep"
  repo-url: https://github.com/jrfep/jrfep.github.io
  repo-branch: mostly-harmless
  repo-actions: [edit, issue]
  navbar:
    title: "J.R. Ferrer-Paris"
    type: inverse
    left:
      - text: "{{< fa gear >}} Homo faber"
        icon: fa-home
        href: index.qmd
      - text: "{{< fa landmark >}} Ciencia y academia"
        menu:
          - text: "Mis publicaciones"
            href: rzrch/my-publications.qmd
          - text: "Productos científicos"
            href: rzrch/research-outputs.qmd
          - text: "Proyectos reproducibles"
            href: rzrch/my-osfr-projects.qmd
          - text: "Repositorios / código"
            href: rzrch/my-github-repos.qmd
          - text: "Eventos"
            href: evnts/evnt-list.qmd
      - text: "{{< fa leaf >}} Biodiversidad"
        menu:
          - text: "Mis ecosistemas favoritos"
            href: ecos/my-favs.qmd
          - text: "Mis especies favoritas"
            href: taxa/my-favs.qmd
      - text: "{{< fa smile >}} Homo ludens"
        menu:
          - text: "Futbol"
            icon: futbol
            href: j4fun/blog_LaLiga_FinalTemp2019.qmd
          - text: "Ulysses"
            icon: book
            href: j4fun/ulysses.qmd
    right:
      - text: "How to..."
        icon: question
        menu:
          - text: "(re-)create this site"
            href: how2/how-to-site.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
lang: es 