project:
  type: website
  output-dir: docs

website:
  title: "today"
  navbar:
    title: "J.R. Ferrer-Paris"
    type: inverse
    left:
      - text: "Inicio"
        icon: fa-home
        href: index.qmd
      - text: "Mi ciencia"
        icon: fa-gear
        menu:
          - text: "Mis publicaciones"
            href: rzrch/my-publications.qmd
          - text: "Productos de investigación"
            href: rzrch/research-outputs.qmd
          - text: "Proyectos reproducibles (Código+Datos)"
            href: rzrch/my-osfr-projects.qmd
          - text: "Repositorios (Código)"
            href: rzrch/my-github-repos.qmd
      - text: "Biodiversidad"
        icon: fa-envira
        menu:
          - text: "Mis especies favoritas"
            href: taxa/my-favs.qmd
          - text: "Observaciones en iNaturalist"
            href: biodv/inat_flexdashboard.Rmd
      - text: "Just for fun"
        icon: fa-smile
        menu:
          - text: "Fútbol"
            icon: fa-futbol
            href: j4fun/blog_LaLiga_FinalTemp2019.qmd
    right:
      - text: "How to..."
        icon: fa-question
        menu:
          - text: "(re-)create this site"
            href: how2/how-to-site.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true