---
title: "Homo faber"
---

[Investigador](https://research.unsw.edu.au/people/dr-jose-rafael-ferrer) en la Universidad de New South Wales, Australia.

Trabajo en el Centro de Estudio de Ecosistemas de la Escuela de Ciencias Biológica, Geológicas y Ambientales.

También soy miembro de la Comisión de Manejo de Ecosistemas de la Unión Internacional para la Conservación de la Naturaleza (UICN) y contribuyo activamente con el [Grupo Temático de Lista Roja de Ecosistemas](https://iucnrle.org/team).

## Mis proyectos 

* Tipología global de ecosystemas
    - [Ecosistemas del mundo](https://global-ecosystems.org/)
    - [Información sobre los mapas](https://jrfep.github.io/Ecosystem-profiles-comments/)
    - [Manglares: Unidades ecoregionales](https://ecosphere.shinyapps.io/Mangrove-L4-map/)
* Lista Roja de Ecosistemas
    - [Glaciares tropicales](https://red-list-ecosystem.github.io/T6.1-SA-01-VE-01-Cordillera-Merida/)
    - [Lista de publicaciones](https://red-list-ecosystem.github.io/RLE-publication-list/)
* [Contribuciones al Centre of Ecosystem Science, UNSW](https://ces-unsw-edu-au.github.io/cesdata/)
* [Fire Ecology Traits for Plants](http://13.54.3.205<b>)
* [NeoMapas](https://neomapas.github.io)


## Perfiles académicos y profesionales

* ORCID: [0000-0002-9554-3395](http://orcid.org/0000-0002-9554-3395)
* Dimensions: [ur.0755224440.38](https://app.dimensions.ai/details/entities/publication/author/ur.0755224440.38)
* Kudos: [Jose Ferrer](https://www.growkudos.com/profile/jose_ferrer)
* Impactstory: [0000-0002-9554-3395](https://profiles.impactstory.org/u/0000-0002-9554-3395)
* Europe PMC: [0000-0002-9554-3395](https://europepmc.org/authors/0000-0002-9554-3395)
* Web of Science/Publons ResearcherID: [M-3785-2015](https://www.webofscience.com/wos/author/rid/M-3785-2015)
* AuthorID de Scopus: [6507728759](http://www.scopus.com/authid/detail.uri?authorId=6507728759)
* ScienceOpen: [jrfep](https://www.scienceopen.com/user/jrfep)
* Google scholar: [A2Thq5UAAAAJ](http://scholar.google.es/citations?user=A2Thq5UAAAAJ&hl=en)
* LinkedIn [Jose Ferrer](https://www.linkedin.com/pub/jos%C3%A9-ferrer/70/a47/547)
* Researchgate: [Jose Ferrer Paris](https://www.researchgate.net/profile/Jose_Ferrer-Paris)
* academia: [JR Ferrer Paris](https://ivic.academia.edu/JRFerrerParis)
* Redalyc: [José R. Ferrer-Paris](https://www.redalyc.org/autor.oa?id=68544)
* Devpost: [jrferrerparis](https://devpost.com/jrferrerparis)


### Taxonomía

* Zoobank: [José R. Ferrer-Paris](http://zoobank.org/Authors/7D3C0AEE-DE5A-4C21-94A1-C16F357890E6)


## Proyectos reproducibles

En los siguientes enlaces pueden encontrar algunos insumos y productos de mi trabajo científico.

* OSF: [José R. Ferrer Paris](https://osf.io/7q5ny)
* figshare: [José R. Ferrer Paris](http://figshare.com/authors/Jos_R_Ferrer_Paris/592994)
* zenodo: 
    - [IUCN Red List of Ecosystems community](https://zenodo.org/communities/iucn-rle/?page=1&size=20)
    - [Monitoreo de biodiversidad en Venezuela](https://zenodo.org/communities/neomapas/?q=&l=list&p=1&s=10&sort=newest)
* dataverse: [NeoMapas dataverse](https://dataverse.harvard.edu/dataverse/NeoMapas)


## Presentaciones

- Algunas recientes en <https://rpubs.com/jrfep>

## Tutoriales

* [UNSW codeRs](https://unsw-coders.netlify.app/)
* Datos geoespaciales en R:
    - [Parte 1](https://ecosphere.shinyapps.io/tutorial-1-create-spatial-object/)
    - [Parte 2](https://ecosphere.shinyapps.io/tutorial-2-points-lines-polygons/)

## Versiones viejas...

Blogger: [José R. Ferrer Paris](https://www.blogger.com/profile/10848423852723434095)
