---
title: "Repositorios de software en GitHub"
output: html_document
editor_options: 
  chunk_output_type: console
---

Usar el API para consultar lista de repositorios
```{r}
library(jsonlite)

gh_rle_org <- read_json("https://api.github.com/orgs/red-list-ecosystem/repos")
gh_ces_org <- read_json("https://api.github.com/orgs/ces-unsw-edu-au/repos")
gh_jrfep <- read_json("https://api.github.com/users/jrfep/repos")
# https://api.github.com/search/repositories?q=user:jrfep&fork:false
# for each repo query the languages_url and summarise the lines of code for each language
```

Función para leer datos de la consulta del API.
```{r}
getItem <- function(x) {
  sprintf("<b><a href='%s'>%s</a></b><p>Description: %s</p>",x$html_url, x$full_name, x$description)
}
```

## Organización `Red List Ecosystems`

```{r, results='asis'}
cat(unlist(lapply(gh_rle_org, getItem)))
```

## Organización `Centre for Ecosystem Sciences`

```{r, results='asis'}
cat(unlist(lapply(gh_ces_org, getItem)))
```

## Repositorios en cuenta personal `jrfep`
```{r, results='asis'}
cat(unlist(lapply(gh_jrfep, getItem)))
```

