---
title: GART/GloBIS Workshop
date: 21 mayo 2003
params:
 ffin: 23 mayo 2003
 code: 2003_GART
 lugar: Stuttgart, Germany
categories:
 - Alemania
 - Ponencia
 - Taller
 - Internacional
---

GART/GloBIS Workshop. Butterfly taxonomy on the internet, issues and challenges of a global, web-based, taxonomic information system. [Stuttgart](/lgrs/Stuttgart.qmd), Germany, 21-23 May 2003.  

[Workshop program and presentations](http://www.insects-online.de/gartfron.htm)

Posterior al taller se consolidó el [Global Butterfly Information System](https://www.gbif.org/dataset/153c2909-ab0b-4e85-b43e-8f6a2a484216), hospedado por el proyecto [Catalogue of Life](https://www.catalogueoflife.org). 


```{r}
#| echo: false
#| warning: false
#| message: false

library(FlickrAPI)
library(pixture)
suppressMessages(library(dplyr))
suppressMessages(here::i_am("lgrs/Trieste.qmd"))

```

```{r}
#| echo: false
file_name <- here::here("data","google-photos.rds")
ggl_photos <- readRDS(file=file_name)
img_folder <- "img"

photos <- ggl_photos %>% 
    filter(
        album %in% "Eventuales",
        grepl("Stuttgart",mediaItems.description))

paths <- sprintf("%s/%s",img_folder, pull(photos,mediaItems.filename))
captions <- photos %>% transmute(caption=sprintf("<strong>%s</strong>  por <a href='%s' target='googlephotos'>JR Ferrer-Paris @ Google Photos</a>",mediaItems.description,mediaItems.productUrl)) %>% pull

pixgallery(paths, caption=captions)

```