---
title: "Water in the ecosphere according to Joyce"
subtitle: "(a crosswalk)"
author: "JR Ferrer-Paris"
date: "04/09/2022"
---
> What in water did Bloom, waterlover, drawer of water, watercarrier, returning to the range, admire?

> Its universality: its democratic equality and constancy to its nature in seeking its own level: <a href='https://global-ecosystems.org/explore/biomes/M2' target='typology'>its vastness in the ocean</a> of Mercator's projection: its <a href='https://global-ecosystems.org/explore/groups/M3.6' target='typology'>unplumbed profundity in the Sundam trench</a> of the Pacific exceeding 8,000 fathoms: the <a href='https://global-ecosystems.org/explore/groups/M2.1' target='typology'>restlessness of its waves and surface particles</a> visiting in turn all points of its seaboard: the independence of its units: the variability of states of sea: its hydrostatic quiescence in calm: its hydrokinetic turgidity in neap and spring tides: its subsidence after devastation: its sterility in the <a href='https://global-ecosystems.org/explore/groups/T6.1' target='typology'>circumpolar icecaps</a>, arctic and antarctic: its climatic and commercial significance: its preponderance of 3 to 1 over the dry land of the globe: its indisputable hegemony extending in square leagues over all the region below the subequatorial tropic of Capricorn: the multisecular stability of its <a href='https://global-ecosystems.org/explore/biomes/M3' target='typology'>primeval basin</a>: its luteofulvous bed: its capacity to dissolve and hold in solution all soluble substances including millions of tons of the most precious metals: its slow erosions of peninsulas and islands, its persistent formation of homothetic islands, peninsulas and downwardtending promontories: its alluvial deposits: its weight and volume and density: its imperturbability in lagoons and highland tarns: its gradation of colours in the torrid and temperate and frigid zones: its vehicular ramifications in continental lakecontained streams and confluent oceanflowing rivers with their tributaries and transoceanic currents, gulfstream, north and south equatorial courses: its violence in seaquakes, waterspouts, <a href='https://global-ecosystems.org/explore/groups/F2.8' target='typology'>Artesian wells</a>, eruptions, torrents, eddies, freshets, spates, groundswells, watersheds, waterpartings, <a href='https://global-ecosystems.org/explore/groups/F2.9' target='typology'>geysers</a>, cataracts, whirlpools, maelstroms, <a href='https://global-ecosystems.org/explore/groups/FT1.4' target='typology'>inundations</a>, deluges, cloudbursts: its vast circumterrestrial ahorizontal curve: its secrecy in springs and latent humidity, revealed by rhabdomantic or hygrometric instruments and exemplified by the hole in the wall at Ashtown gate, saturation of air, distillation of dew: the simplicity of its composition, two constituent parts of hydrogen with one constituent part of oxygen: its healing virtues: its buoyancy in the <a href='https://global-ecosystems.org/explore/groups/F2.6' target='typology'>waters of the Dead Sea</a>: its persevering penetrativeness in runnels, gullies, <a href='https://global-ecosystems.org/explore/groups/F3.1' target='typology'>inadequate dams</a>, leaks on shipboard: its properties for cleansing, quenching thirst and fire, nourishing vegetation: its infallibility as paradigm and paragon: its metamorphoses as vapour, mist, cloud, rain, sleet, snow, hail: its strength in rigid hydrants: its variety of forms in loughs and bays and gulfs and bights and guts and lagoons and atolls and archipelagos and <a href='https://global-ecosystems.org/explore/groups/FM1.3' target='typology'>sounds and fjords</a> and minches and tidal estuaries and arms of sea: its solidity in glaciers, icebergs, <a href='https://global-ecosystems.org/explore/groups/M2.5' target='typology'>icefloes</a>: its docility in working hydraulic millwheels, turbines, dynamos, electric power stations, bleachworks, tanneries, scutchmills: its utility in canals, rivers, if navigable, floating and graving docks: its potentiality derivable from harnessed tides or watercourses falling from level to level: its submarine fauna and flora (anacoustic, photophobe), numerically, if not literally, the inhabitants of the globe: its ubiquity as constituting 90% of the human body: the noxiousness of its effluvia in <a href='https://global-ecosystems.org/explore/groups/FT1.3' target='typology'>lacustrine marshes</a>, <a href='https://global-ecosystems.org/explore/groups/FT1.7' target='typology'>pestilential fens</a>, faded flowerwater, stagnant pools in the waning moon.

James Joyce - Ulysses, 1922
