---
title: "Bosques secos tropicales"
bibliography: 
  - ../bibTeX/peer-review.bibtex
---

Según la descripción de la Tipología Global de Ecosistemas de la UICN:

> Los bosques y matorrales secos tropicales y subtropicales ([T1.2 Tropical-subtropical dry forests and thickets](https://global-ecosystems.org/explore/groups/T1.2)) se caracterizan por substratos fertiles y condiciones secas estacionales (cerca de 1800 mm de precipitación anual con periodos de 3 a 6 meses con menos de 100mm al mes) que conduce a marcados patrones estacionales de productividad. La diversidad arborea es alta, con una variable mezcla de especies decíduas y estacionales, abundantes lianas pero menos epífitas, helechos, musgos y hierbas limitados por la sequía estacional. Dentro de las complejas redes tróficas diferentes grupos de vertebrados tienen roles dominantes, mientras que los hongos y microbios se encargan de descomponer la abundante hojarasca.



Burro Negro [@Moran2018]

En Myanmar [@Murray_2020_RLE_Myanmar]

En Africa [@RLE_Africa]

En las Americas [@Ferrer-Paris_2019_RLE_Forests]



