---
title: "Glaciares tropicales"
categories:
  - T6.1
bibliography: 
  - ../bibTeX/preprints.bibtex
---

Glaciar tropical de la Cordillera de Mérida [@Ferrer-Paris_Llambi_Melfo_Keith_2023]

Tropical glaciers are fascinating and dynamic ecosystems on top of the highest tropical mountains. Over geological epochs, the snowfall has accumulated and compacted to form massive blocks of ice that grind against the rocky substrate. The friction below the ice, combined with the effect of wind and radiation above, forces the ice to melt. Water drips downstream to form proglacial streams and lakes, rock becomes sediment. It is a harsh environment, yet life persists in diverse forms – from microscopic algae and bacteria to mesoscale invertebrates – drawing sustenance from sunlight and windfall, defying freezing temperatures with remarkable adaptations and flowing downwards and onwards with the water and the wind. 
Glaciers are poetic landmarks in the tropical landscapes of the Andes. They inspire tales of frozen mythical creatures and serve as origin stories for local legends. These icy giants captivate painters, explorers, poets and scientists alike. Glacial ice seems solid and permanent, but it is actually water flowing at an imperceptibly slow pace. A single drop of water freezing on the glacier’s surface will spend years, even decades moving downwards before eventually leaving the glacier. The ice seems inert and frigid, but is teeming with small organisms. A delicate balance of inputs and outputs, a connection between the clouds and earth. An almost impossible balance considering the tropical landscape that surrounds them.
And most likely this balance is already broken. The ice that accumulated over millennia and centuries is melting faster and the input from new snowfall falls short of compensating for the loss. For years now there has been multiple warnings about the imminent disappearance of tropical glaciers. In fact, some have already been loss leaving just a memory. In some regions the remnants are too small, the declining trends too swift, and the drivers too strong for any hope.
Cycles of positive and negative ice mass balance are part of the history of tropical glaciers. Geological evidence over very large timescales show: wet and cold years are good for accumulation of ice; dry and hot years increase melting and the glacier shrink. The slow pace of these changes has left profound marks in our landscapes. But human induced climate change and air pollution are likely exacerbating melting processes and inhibiting accumulation processes in a completely different time scales. 
Most contemporary witnesses have only seen the sustained decline over the last 100 or 50 years. And the further these declines progress, the more pronounced they become. Until they bring the glaciers to an abrupt and catastrophic halt. As glaciers recede faster, they become increasingly vulnerable. A shrinking, fractured ice mass succumbs more readily to negative effects of radiation, pollution and wind. As the ice disappears, it thins, it can no longer interact with the rock. Water flow dwindles, unable to carry sediment. The once-dynamic ecosystem stagnates and we don’t know what comes next.

Our understanding of glacier ecosystems remains limited. When glaciers retreat new biotic communities gradually assemble. But how fast? How slow? Plants and animals from surrounding environments will colonise. Will this be a rich and diverse community? Will it be dominated by opportunistic and ruderal species? Will the specialised glacier biota survive? Will they find a cold refuge elsewhere?

The tropical glacier ecosystem of the Cordillera de Merida in Venezuela is the first of its kind to be assessed using the IUCN Red List of Ecosystem protocol. In the months since completing the assessment, it has continued to shrink dramatically. Last-ditch efforts to protect it cannot cope with the relentless forces driving its demise. This is sadly the fate that awaits other tropical glaciers in the world. 
